// CareCoach Pro — Partner-Repository: LocalStorage-Persistenz + Seed-Daten
import type { Partner } from '@/domain/types';

export const PARTNER_STORAGE_KEY = 'ccpro_partner';

export const PARTNER_SEED: Partner[] = [
  {
    id: 'p1',
    typ: 'pflegedienst',
    firmenname: 'Hauspflege Staaken GbR',
    geschaeftsfuehrer: 'Leonid Dolgoj / Gennadij Mandel',
    strasse: 'Fachinger Straße 39A',
    plz: '13591',
    ort: 'Berlin',
    bundesland: 'berlin',
    bezirk: 'Spandau',
    telefon: '030 36704054',
    fax: '030 36704056',
    email: 'info@hkp-staaken.de',
    website: 'hkp-staaken.de',
    leistungen: 'Ambulante Pflege / Intensivpflege / Nachtpflege / Hauswirtschaft',
    paragraph72_zugelassen: true,
    sprachen: 'Deutsch / Russisch',
    kooperations_status: 'Offen',
    crm_status: 'Neu',
    notiz: 'Bekannter Kontakt – persönliche Ansprache empfohlen',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p2',
    typ: 'pflegedienst',
    firmenname: 'Ambulanter Pflegedienst Herzensgüte GmbH',
    geschaeftsfuehrer: 'Igor Vaxer',
    strasse: 'Jahnstraße 8',
    plz: '24116',
    ort: 'Kiel',
    bundesland: 'schleswig_holstein',
    telefon: '0431 98283211',
    fax: '0431 98283213',
    email: 'info@pflegedienst-herzensguete.de',
    leistungen: 'Ambulante Pflege / Behandlungspflege / Grundpflege / Hauswirtschaft / Beratung',
    paragraph72_zugelassen: true,
    sprachen: 'Deutsch / Russisch',
    kooperations_status: 'Offen',
    crm_status: 'Neu',
    notiz: 'Priorität Kiel',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p3',
    typ: 'pflegedienst',
    firmenname: 'RENAFAN Ambulante Pflege Charlottenburg',
    geschaeftsfuehrer: 'Shaodong Fan / Gordana Markovic / Marco Prinz',
    strasse: 'Berliner Straße 39',
    plz: '10715',
    ort: 'Berlin',
    bundesland: 'berlin',
    bezirk: 'Charlottenburg-Wilmersdorf',
    telefon: '030 30102120',
    fax: '030 30102140',
    email: 'charlottenburg@renafan.de',
    website: 'renafan.de',
    hrb: '130027',
    ust_id: 'DE262105074',
    paragraph72_zugelassen: true,
    patienten_ca: 105,
    sprachen: 'Deutsch / Russisch',
    kooperations_status: 'Offen',
    crm_status: 'Neu',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p4',
    typ: 'pflegedienst',
    firmenname: 'Ambulanter Pflegedienst DAKOS',
    geschaeftsfuehrer: 'Daniil Buylenko',
    strasse: 'Otto-Suhr-Allee 110',
    plz: '10585',
    ort: 'Berlin',
    bundesland: 'berlin',
    bezirk: 'Charlottenburg',
    telefon: '030 53088150',
    mobil: '0176 49490073',
    fax: '030 53088618',
    email: 'info@pflegedienst-dakos.de',
    paragraph72_zugelassen: true,
    sprachen: 'Deutsch / Russisch / Polnisch / Serbisch / Englisch',
    kooperations_status: 'Offen',
    crm_status: 'Neu',
    notiz: 'Gegründet 2012, 24h erreichbar',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p5',
    typ: 'pflegedienst',
    firmenname: 'AlexA Ambulante Pflege Berlin-Pankow',
    geschaeftsfuehrer: 'Harald Berghoff',
    strasse: 'Wolfshagener Straße 135',
    plz: '13187',
    ort: 'Berlin',
    bundesland: 'berlin',
    bezirk: 'Pankow',
    telefon: '030 48637809',
    fax: '030 48637819',
    email: 'pankow@alexa-pflege.de',
    hrb: 'HRB 74049',
    paragraph72_zugelassen: true,
    kooperations_status: 'Offen',
    crm_status: 'Neu',
    notiz: 'Standortleiter David Göschel 0160 93544118',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p6',
    typ: 'pflegedienst',
    firmenname: 'Spreevital Häuslicher Pflegedienst GmbH',
    ort: 'Berlin',
    bundesland: 'berlin',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p7',
    typ: 'pflegedienst',
    firmenname: 'Ambulanter Pflegedienst Kuffel Care GmbH',
    ort: 'Berlin',
    bundesland: 'berlin',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p8',
    typ: 'pflegedienst',
    firmenname: 'APB GO GmbH Ambulantes Pflegezentrum Berlin',
    ort: 'Berlin',
    bundesland: 'berlin',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p9',
    typ: 'pflegedienst',
    firmenname: 'Pflegewelt-Berlin-Mitte GmbH',
    ort: 'Berlin',
    bundesland: 'berlin',
    bezirk: 'Mitte',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p10',
    typ: 'pflegedienst',
    firmenname: 'Deutsche Seniorenbetreuung Berlin',
    ort: 'Berlin',
    bundesland: 'berlin',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p11',
    typ: 'pflegedienst',
    firmenname: 'Ambulanter Pflegedienst Patria Berlin',
    ort: 'Berlin',
    bundesland: 'berlin',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p12',
    typ: 'pflegedienst',
    firmenname: 'Ambulanter Pflegedienst MediJan GmbH',
    ort: 'Berlin',
    bundesland: 'berlin',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p13',
    typ: 'pflegedienst',
    firmenname: 'PSL Ihr Pflegedienst für Stadt und Land GmbH',
    ort: 'Potsdam-Mittelmark',
    bundesland: 'brandenburg',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p14',
    typ: 'pflegedienst',
    firmenname: 'Tagespflege Havel',
    ort: 'Havelland',
    bundesland: 'brandenburg',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p15',
    typ: 'pflegedienst',
    firmenname: 'Future Care',
    ort: 'Brandenburg',
    bundesland: 'brandenburg',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p16',
    typ: 'pflegedienst',
    firmenname: 'AD Ambulante Dienste gGmbH',
    ort: 'Kiel',
    bundesland: 'schleswig_holstein',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p17',
    typ: 'pflegedienst',
    firmenname: 'Aktiv Pflege Nord',
    ort: 'Kiel',
    bundesland: 'schleswig_holstein',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p18',
    typ: 'pflegedienst',
    firmenname: 'Altenhilfe zu Hause e.V.',
    ort: 'Kiel',
    bundesland: 'schleswig_holstein',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p19',
    typ: 'pflegedienst',
    firmenname: 'Ambulante Pflege am Meer',
    ort: 'Kiel',
    bundesland: 'schleswig_holstein',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p20',
    typ: 'pflegedienst',
    firmenname: 'Ambulanter Pflegedienst Vita Fit',
    ort: 'Kiel',
    bundesland: 'schleswig_holstein',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p21',
    typ: 'pflegedienst',
    firmenname: 'Ambulanter Pflegedienst Harmonie',
    ort: 'Kiel',
    bundesland: 'schleswig_holstein',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p22',
    typ: 'pflegedienst',
    firmenname: 'Ambulanter Pflegedienst Pflege Direkt',
    ort: 'Kiel',
    bundesland: 'schleswig_holstein',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p23',
    typ: 'pflegedienst',
    firmenname: 'PNT Pflegedienste Kiel',
    ort: 'Kiel',
    bundesland: 'schleswig_holstein',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p24',
    typ: 'pflegedienst',
    firmenname: 'IDEL GmbH',
    strasse: 'Holsteinische Str. 52',
    plz: '10717',
    ort: 'Berlin',
    bundesland: 'berlin',
    bezirk: 'Wilmersdorf',
    telefon: '030 95601930',
    website: 'idel-pflege.de',
    hrb: '185052',
    paragraph72_zugelassen: true,
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    notiz: 'Gegründet 2017',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p25',
    typ: 'pflegedienst',
    firmenname: 'Oxalis GmbH',
    strasse: 'Fechnerstraße 6A',
    plz: '10717',
    ort: 'Berlin',
    bundesland: 'berlin',
    bezirk: 'Wilmersdorf',
    telefon: '030 86313613',
    fax: '030 86313606',
    email: 'oxalis.pflegedienst@googlemail.com',
    hrb: '89539',
    paragraph72_zugelassen: true,
    patienten_ca: 78,
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    notiz: 'Intensivpflege-WG, 6km Einsatzgebiet',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p26',
    typ: 'pflegedienst',
    firmenname: 'Tagespflege am Lankwitzer Ufer GmbH',
    strasse: 'Kaiser-Wilhelm-Str. 129A',
    plz: '12247',
    ort: 'Berlin',
    bundesland: 'berlin',
    bezirk: 'Steglitz-Zehlendorf',
    geschaeftsfuehrer: 'Maria Belsky / Vladimir Boguslavski',
    hrb: '260850',
    paragraph72_zugelassen: true,
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    notiz: 'Gegründet 2024 – russischsprachige GF',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  // --- Pflegekassen ---
  {
    id: 'kk1',
    typ: 'pflegekasse',
    firmenname: 'AOK Nordost',
    geschaeftsfuehrer: 'Frank Michalak',
    strasse: 'Wilhelmstraße 1',
    plz: '10963',
    ort: 'Berlin',
    bundesland: 'berlin',
    telefon: '030 34646-0',
    email: 'pflegekasse@aok-nordost.de',
    ik_nummer: '104212505',
    leistungen: 'Pflegekasse §40 SGB XI / §45b SGB XI — Leitkasse Berlin',
    kooperations_status: 'Kontaktiert',
    crm_status: 'In Gespräch',
    notiz: 'Leitkasse Berlin / AOK Nordost — wichtigster Förderpartner für §40-Anträge',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  // --- Krankenkassen ---
  {
    id: 'kk2',
    typ: 'krankenkasse',
    firmenname: 'Techniker Krankenkasse (TK)',
    strasse: 'Bramfelder Straße 140',
    plz: '22305',
    ort: 'Hamburg',
    bundesland: 'sonstige',
    telefon: '040 6909-0',
    email: 'service@tk.de',
    ik_nummer: '101575519',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'kk3',
    typ: 'krankenkasse',
    firmenname: 'Barmer',
    strasse: 'Axel-Springer-Straße 44',
    plz: '10969',
    ort: 'Berlin',
    bundesland: 'berlin',
    telefon: '0800 333 1010',
    ik_nummer: '104212059',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'kk4',
    typ: 'krankenkasse',
    firmenname: 'DAK-Gesundheit',
    strasse: 'Nagelsweg 27-31',
    plz: '20097',
    ort: 'Hamburg',
    bundesland: 'sonstige',
    telefon: '040 325 325 325',
    ik_nummer: '105313894',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'kk5',
    typ: 'krankenkasse',
    firmenname: 'KKH Kaufmännische Krankenkasse',
    strasse: 'Karl-Wiechert-Allee 61',
    plz: '30625',
    ort: 'Hannover',
    bundesland: 'sonstige',
    telefon: '0800 200 400 1',
    ik_nummer: '102171012',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'kk6',
    typ: 'krankenkasse',
    firmenname: 'hkk',
    strasse: 'Martinistraße 26',
    plz: '28195',
    ort: 'Bremen',
    bundesland: 'sonstige',
    telefon: '0421 3655-0',
    ik_nummer: '103724250',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'kk7',
    typ: 'krankenkasse',
    firmenname: 'BKK VBU',
    strasse: 'Lindenstraße 67',
    plz: '10969',
    ort: 'Berlin',
    bundesland: 'berlin',
    telefon: '030 72612-0',
    ik_nummer: '104212505',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'kk8',
    typ: 'krankenkasse',
    firmenname: 'IKK classic',
    strasse: 'Tannenstraße 4b',
    plz: '01099',
    ort: 'Dresden',
    bundesland: 'sonstige',
    telefon: '0800 455 1111',
    ik_nummer: '101317386',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'kk9',
    typ: 'krankenkasse',
    firmenname: 'Knappschaft',
    strasse: 'Pieperstraße 14-28',
    plz: '44789',
    ort: 'Bochum',
    bundesland: 'sonstige',
    telefon: '0234 304-0',
    ik_nummer: '120390008',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'kk10',
    typ: 'krankenkasse',
    firmenname: 'AOK Bayern',
    strasse: 'Carl-Wery-Straße 28',
    plz: '81739',
    ort: 'München',
    bundesland: 'sonstige',
    telefon: '089 627300',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'kk11',
    typ: 'krankenkasse',
    firmenname: 'AOK Baden-Württemberg',
    strasse: 'Heilbronner Straße 184',
    plz: '70191',
    ort: 'Stuttgart',
    bundesland: 'sonstige',
    telefon: '0711 2593-0',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'kk12',
    typ: 'krankenkasse',
    firmenname: 'AOK Plus (Sachsen/Thüringen)',
    strasse: 'Sternplatz 7',
    plz: '01067',
    ort: 'Dresden',
    bundesland: 'sonstige',
    telefon: '0800 10590-00',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'kk13',
    typ: 'krankenkasse',
    firmenname: 'AOK Rheinland/Hamburg',
    strasse: 'Kaiserstraße 170',
    plz: '47259',
    ort: 'Duisburg',
    bundesland: 'sonstige',
    telefon: '0211 8791-0',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'kk14',
    typ: 'krankenkasse',
    firmenname: 'AOK Niedersachsen',
    strasse: 'Hildesheimer Straße 1',
    plz: '30559',
    ort: 'Hannover',
    bundesland: 'sonstige',
    telefon: '0511 8701-0',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'kk15',
    typ: 'krankenkasse',
    firmenname: 'AOK NordWest',
    strasse: 'Kopenhagener Straße 1',
    plz: '44269',
    ort: 'Dortmund',
    bundesland: 'sonstige',
    telefon: '0231 5403-0',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'kk16',
    typ: 'krankenkasse',
    firmenname: 'AOK Hessen',
    strasse: 'Berner Straße 2',
    plz: '60437',
    ort: 'Frankfurt',
    bundesland: 'sonstige',
    telefon: '069 8062-0',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'kk17',
    typ: 'krankenkasse',
    firmenname: 'AOK Sachsen-Anhalt',
    strasse: 'Karl-Marx-Straße 1',
    plz: '39104',
    ort: 'Magdeburg',
    bundesland: 'sonstige',
    telefon: '0391 2800-0',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'kk18',
    typ: 'krankenkasse',
    firmenname: 'Vivantes BKK',
    strasse: 'Wenckebachstraße 23',
    plz: '12099',
    ort: 'Berlin',
    bundesland: 'berlin',
    telefon: '030 130 19-0',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'kk19',
    typ: 'krankenkasse',
    firmenname: 'SBK Siemens Betriebskrankenkasse',
    strasse: 'Hofmannstraße 51',
    plz: '81379',
    ort: 'München',
    bundesland: 'sonstige',
    telefon: '089 6279-0',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'kk20',
    typ: 'krankenkasse',
    firmenname: 'BAHN-BKK',
    strasse: 'Franklinstraße 54',
    plz: '60486',
    ort: 'Frankfurt',
    bundesland: 'sonstige',
    telefon: '069 97303-0',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
];

export function ladePartner(): Partner[] {
  try {
    const roh = localStorage.getItem(PARTNER_STORAGE_KEY);
    if (roh) {
      const daten = JSON.parse(roh) as Partner[];
      if (Array.isArray(daten) && daten.length > 0) return daten;
    }
  } catch {
    // Beschädigte Daten ignorieren.
  }
  return PARTNER_SEED;
}

export function speicherePartner(partner: Partner[]): void {
  localStorage.setItem(PARTNER_STORAGE_KEY, JSON.stringify(partner));
}
