// CareCoach Pro — Partner-Repository: LocalStorage-Persistenz + Seed-Daten
import type { Partner } from '@/domain/types';

export const PARTNER_STORAGE_KEY = 'ccpro_partner';

export const PARTNER_SEED: Partner[] = [
  {
    id: 'p1',
    typ: 'pflegedienst',
    firmenname: 'Hauspflege Staaken GbR',
    geschaeftsfuehrer: 'Leonid Dolgoj / Gennadij Mandel',
    strasse: 'Fachinger Straße 39A',
    plz: '13591',
    ort: 'Berlin',
    bundesland: 'berlin',
    bezirk: 'Spandau',
    telefon: '030 36704054',
    fax: '030 36704056',
    email: 'info@hkp-staaken.de',
    website: 'hkp-staaken.de',
    leistungen: 'Ambulante Pflege / Intensivpflege / Nachtpflege / Hauswirtschaft',
    paragraph72_zugelassen: true,
    sprachen: 'Deutsch / Russisch',
    kooperations_status: 'Offen',
    crm_status: 'Neu',
    notiz: 'Bekannter Kontakt – persönliche Ansprache empfohlen',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p2',
    typ: 'pflegedienst',
    firmenname: 'Ambulanter Pflegedienst Herzensgüte GmbH',
    geschaeftsfuehrer: 'Igor Vaxer',
    strasse: 'Jahnstraße 8',
    plz: '24116',
    ort: 'Kiel',
    bundesland: 'schleswig_holstein',
    telefon: '0431 98283211',
    fax: '0431 98283213',
    email: 'info@pflegedienst-herzensguete.de',
    leistungen: 'Ambulante Pflege / Behandlungspflege / Grundpflege / Hauswirtschaft / Beratung',
    paragraph72_zugelassen: true,
    sprachen: 'Deutsch / Russisch',
    kooperations_status: 'Offen',
    crm_status: 'Neu',
    notiz: 'Priorität Kiel',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p3',
    typ: 'pflegedienst',
    firmenname: 'RENAFAN Ambulante Pflege Charlottenburg',
    geschaeftsfuehrer: 'Shaodong Fan / Gordana Markovic / Marco Prinz',
    strasse: 'Berliner Straße 39',
    plz: '10715',
    ort: 'Berlin',
    bundesland: 'berlin',
    bezirk: 'Charlottenburg-Wilmersdorf',
    telefon: '030 30102120',
    fax: '030 30102140',
    email: 'charlottenburg@renafan.de',
    website: 'renafan.de',
    hrb: '130027',
    ust_id: 'DE262105074',
    paragraph72_zugelassen: true,
    patienten_ca: 105,
    sprachen: 'Deutsch / Russisch',
    kooperations_status: 'Offen',
    crm_status: 'Neu',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p4',
    typ: 'pflegedienst',
    firmenname: 'Ambulanter Pflegedienst DAKOS',
    geschaeftsfuehrer: 'Daniil Buylenko',
    strasse: 'Otto-Suhr-Allee 110',
    plz: '10585',
    ort: 'Berlin',
    bundesland: 'berlin',
    bezirk: 'Charlottenburg',
    telefon: '030 53088150',
    mobil: '0176 49490073',
    fax: '030 53088618',
    email: 'info@pflegedienst-dakos.de',
    paragraph72_zugelassen: true,
    sprachen: 'Deutsch / Russisch / Polnisch / Serbisch / Englisch',
    kooperations_status: 'Offen',
    crm_status: 'Neu',
    notiz: 'Gegründet 2012, 24h erreichbar',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p5',
    typ: 'pflegedienst',
    firmenname: 'AlexA Ambulante Pflege Berlin-Pankow',
    geschaeftsfuehrer: 'Harald Berghoff',
    strasse: 'Wolfshagener Straße 135',
    plz: '13187',
    ort: 'Berlin',
    bundesland: 'berlin',
    bezirk: 'Pankow',
    telefon: '030 48637809',
    fax: '030 48637819',
    email: 'pankow@alexa-pflege.de',
    hrb: 'HRB 74049',
    paragraph72_zugelassen: true,
    kooperations_status: 'Offen',
    crm_status: 'Neu',
    notiz: 'Standortleiter David Göschel 0160 93544118',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p6',
    typ: 'pflegedienst',
    firmenname: 'Spreevital Häuslicher Pflegedienst GmbH',
    ort: 'Berlin',
    bundesland: 'berlin',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p7',
    typ: 'pflegedienst',
    firmenname: 'Ambulanter Pflegedienst Kuffel Care GmbH',
    ort: 'Berlin',
    bundesland: 'berlin',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p8',
    typ: 'pflegedienst',
    firmenname: 'APB GO GmbH Ambulantes Pflegezentrum Berlin',
    ort: 'Berlin',
    bundesland: 'berlin',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p9',
    typ: 'pflegedienst',
    firmenname: 'Pflegewelt-Berlin-Mitte GmbH',
    ort: 'Berlin',
    bundesland: 'berlin',
    bezirk: 'Mitte',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p10',
    typ: 'pflegedienst',
    firmenname: 'Deutsche Seniorenbetreuung Berlin',
    ort: 'Berlin',
    bundesland: 'berlin',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p11',
    typ: 'pflegedienst',
    firmenname: 'Ambulanter Pflegedienst Patria Berlin',
    ort: 'Berlin',
    bundesland: 'berlin',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p12',
    typ: 'pflegedienst',
    firmenname: 'Ambulanter Pflegedienst MediJan GmbH',
    ort: 'Berlin',
    bundesland: 'berlin',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p13',
    typ: 'pflegedienst',
    firmenname: 'PSL Ihr Pflegedienst für Stadt und Land GmbH',
    ort: 'Potsdam-Mittelmark',
    bundesland: 'brandenburg',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p14',
    typ: 'pflegedienst',
    firmenname: 'Tagespflege Havel',
    ort: 'Havelland',
    bundesland: 'brandenburg',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p15',
    typ: 'pflegedienst',
    firmenname: 'Future Care',
    ort: 'Brandenburg',
    bundesland: 'brandenburg',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p16',
    typ: 'pflegedienst',
    firmenname: 'AD Ambulante Dienste gGmbH',
    ort: 'Kiel',
    bundesland: 'schleswig_holstein',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p17',
    typ: 'pflegedienst',
    firmenname: 'Aktiv Pflege Nord',
    ort: 'Kiel',
    bundesland: 'schleswig_holstein',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p18',
    typ: 'pflegedienst',
    firmenname: 'Altenhilfe zu Hause e.V.',
    ort: 'Kiel',
    bundesland: 'schleswig_holstein',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p19',
    typ: 'pflegedienst',
    firmenname: 'Ambulante Pflege am Meer',
    ort: 'Kiel',
    bundesland: 'schleswig_holstein',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p20',
    typ: 'pflegedienst',
    firmenname: 'Ambulanter Pflegedienst Vita Fit',
    ort: 'Kiel',
    bundesland: 'schleswig_holstein',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p21',
    typ: 'pflegedienst',
    firmenname: 'Ambulanter Pflegedienst Harmonie',
    ort: 'Kiel',
    bundesland: 'schleswig_holstein',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p22',
    typ: 'pflegedienst',
    firmenname: 'Ambulanter Pflegedienst Pflege Direkt',
    ort: 'Kiel',
    bundesland: 'schleswig_holstein',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
  {
    id: 'p23',
    typ: 'pflegedienst',
    firmenname: 'PNT Pflegedienste Kiel',
    ort: 'Kiel',
    bundesland: 'schleswig_holstein',
    kooperations_status: 'Offen',
    crm_status: 'Recherche',
    aktiv: true,
    erstellt_am: '2026-06-13',
  },
];

export function ladePartner(): Partner[] {
  try {
    const roh = localStorage.getItem(PARTNER_STORAGE_KEY);
    if (roh) {
      const daten = JSON.parse(roh) as Partner[];
      if (Array.isArray(daten) && daten.length > 0) return daten;
    }
  } catch {
    // Beschädigte Daten ignorieren.
  }
  return PARTNER_SEED;
}

export function speicherePartner(partner: Partner[]): void {
  localStorage.setItem(PARTNER_STORAGE_KEY, JSON.stringify(partner));
}
