// CareCoach Pro — Stammdaten-Seed (Phase 2)
// Kassen, Pflegeunternehmen, Dienstleister sowie die Recht-/Prozess-Kataloge
// (Nachweistypen, Pflichtnachweismatrix, Fristen, Ablehnungs-/Widerspruchsgründe).
// Quelle: docs/CRM-Datenmodell.md + docs/Massnahmenkatalog-v1.md.

import type {
  Kasse,
  Pflegeunternehmen,
  Dienstleister,
  NachweisTyp,
  NachweisAnforderung,
  FristRegel,
  Ablehnungsgrund,
  Widerspruchsgrund,
  DokumentVorlage,
} from './types';

// --- Kranken-/Pflegekassen (Berlin-Schwerpunkt) ---
export const KASSEN: Kasse[] = [
  {
    id: 'ka-aok-nordost',
    name: 'AOK Nordost',
    kassenart: 'beides',
    traegergruppe: 'aok',
    ik_nummer: '109519005',
    strasse: 'Wilhelmstraße 1',
    plz: '10963',
    ort: 'Berlin',
    telefon: '0800 2650800',
    fax: '030 20251000',
    email: 'service@nordost.aok.de',
    postanschrift_antraege: 'AOK Nordost – Pflegekasse, 10957 Berlin',
    elektronischer_eingang: 'https://www.aok.de/pk/nordost/',
    akzeptiert_abtretung: true,
    standard_frist_tage: 21,
    frist_mit_md_tage: 35,
    ansprechpartner: [
      {
        name: 'Frau Wagner',
        abteilung: 'Pflegeleistungen',
        telefon: '030 20251234',
        email: 'pflege@nordost.aok.de',
        zustaendig_fuer: '§40 Wohnumfeld',
      },
    ],
    notiz: 'Leitkasse Berlin. Hohe §40-Fallzahl.',
    aktiv: true,
  },
  {
    id: 'ka-barmer',
    name: 'Barmer',
    kassenart: 'beides',
    traegergruppe: 'ersatzkasse',
    ik_nummer: '104940005',
    strasse: 'Axel-Springer-Straße 44',
    plz: '10969',
    ort: 'Berlin',
    telefon: '0800 3331010',
    fax: '0800 3331011',
    email: 'service@barmer.de',
    postanschrift_antraege: 'Barmer Pflegekasse, 42266 Wuppertal',
    elektronischer_eingang: 'https://www.barmer.de/',
    akzeptiert_abtretung: true,
    standard_frist_tage: 21,
    frist_mit_md_tage: 35,
    ansprechpartner: [
      {
        name: 'Herr Dr. Becker',
        abteilung: 'Pflegekasse',
        telefon: '0800 3331020',
        email: 'pflege@barmer.de',
        zustaendig_fuer: '§40 Wohnumfeld',
      },
    ],
    notiz: '',
    aktiv: true,
  },
  {
    id: 'ka-tk',
    name: 'Techniker Krankenkasse',
    kassenart: 'beides',
    traegergruppe: 'ersatzkasse',
    ik_nummer: '101575519',
    strasse: 'Bramfelder Straße 140',
    plz: '22305',
    ort: 'Hamburg',
    telefon: '0800 2858585',
    fax: '040 460655551',
    email: 'service@tk.de',
    postanschrift_antraege: 'Techniker Krankenkasse – Pflegekasse, 22291 Hamburg',
    elektronischer_eingang: 'https://www.tk.de/',
    akzeptiert_abtretung: true,
    standard_frist_tage: 21,
    frist_mit_md_tage: 35,
    ansprechpartner: [
      {
        name: 'Frau Schmidt',
        abteilung: 'Pflegeleistungen',
        telefon: '0800 2858586',
        email: 'pflege@tk.de',
        zustaendig_fuer: '§40 Wohnumfeld',
      },
    ],
    notiz: '',
    aktiv: true,
  },
  {
    id: 'ka-dak',
    name: 'DAK-Gesundheit',
    kassenart: 'beides',
    traegergruppe: 'ersatzkasse',
    ik_nummer: '101570104',
    strasse: 'Nagelsweg 27-31',
    plz: '20097',
    ort: 'Hamburg',
    telefon: '040 325325555',
    fax: '040 325325000',
    email: 'service@dak.de',
    postanschrift_antraege: 'DAK-Gesundheit Pflegekasse, 20097 Hamburg',
    elektronischer_eingang: 'https://www.dak.de/',
    akzeptiert_abtretung: true,
    standard_frist_tage: 21,
    frist_mit_md_tage: 35,
    ansprechpartner: [],
    notiz: '',
    aktiv: true,
  },
  {
    id: 'ka-ikk-classic',
    name: 'IKK classic',
    kassenart: 'beides',
    traegergruppe: 'ikk',
    ik_nummer: '101317386',
    strasse: '',
    plz: '',
    ort: 'Dresden',
    telefon: '',
    fax: '',
    email: '',
    postanschrift_antraege: '',
    elektronischer_eingang: 'https://www.ikk-classic.de/',
    akzeptiert_abtretung: true,
    standard_frist_tage: 21,
    frist_mit_md_tage: 35,
    ansprechpartner: [],
    notiz: '⚠︎ Kontaktdaten (Anschrift/Telefon/E-Mail) ergänzen.',
    aktiv: true,
  },
  {
    id: 'ka-kkh',
    name: 'KKH Kaufmännische Krankenkasse',
    kassenart: 'beides',
    traegergruppe: 'ersatzkasse',
    ik_nummer: '101575519',
    strasse: '',
    plz: '',
    ort: 'Hannover',
    telefon: '',
    fax: '',
    email: '',
    postanschrift_antraege: '',
    elektronischer_eingang: 'https://www.kkh.de/',
    akzeptiert_abtretung: true,
    standard_frist_tage: 21,
    frist_mit_md_tage: 35,
    ansprechpartner: [],
    notiz: '⚠︎ Kontaktdaten (Anschrift/Telefon/E-Mail) ergänzen.',
    aktiv: true,
  },
  {
    id: 'ka-hkk',
    name: 'hkk Krankenkasse',
    kassenart: 'beides',
    traegergruppe: 'ersatzkasse',
    ik_nummer: '103724250',
    strasse: '',
    plz: '',
    ort: 'Bremen',
    telefon: '',
    fax: '',
    email: '',
    postanschrift_antraege: '',
    elektronischer_eingang: 'https://www.hkk.de/',
    akzeptiert_abtretung: true,
    standard_frist_tage: 21,
    frist_mit_md_tage: 35,
    ansprechpartner: [],
    notiz: '⚠︎ Kontaktdaten (Anschrift/Telefon/E-Mail) ergänzen.',
    aktiv: true,
  },
  {
    id: 'ka-bkk-vbu',
    name: 'BKK·VBU',
    kassenart: 'beides',
    traegergruppe: 'bkk',
    ik_nummer: '104212505',
    strasse: '',
    plz: '',
    ort: 'Berlin',
    telefon: '',
    fax: '',
    email: '',
    postanschrift_antraege: '',
    elektronischer_eingang: 'https://www.meine-krankenkasse.de/',
    akzeptiert_abtretung: true,
    standard_frist_tage: 21,
    frist_mit_md_tage: 35,
    ansprechpartner: [],
    notiz: '⚠︎ Kontaktdaten (Anschrift/Telefon/E-Mail) ergänzen.',
    aktiv: true,
  },
  {
    id: 'ka-knappschaft',
    name: 'Knappschaft',
    kassenart: 'beides',
    traegergruppe: 'knappschaft',
    ik_nummer: '120390008',
    strasse: '',
    plz: '',
    ort: 'Bochum',
    telefon: '',
    fax: '',
    email: '',
    postanschrift_antraege: '',
    elektronischer_eingang: 'https://www.knappschaft.de/',
    akzeptiert_abtretung: true,
    standard_frist_tage: 21,
    frist_mit_md_tage: 35,
    ansprechpartner: [],
    notiz: '⚠︎ Kontaktdaten (Anschrift/Telefon/E-Mail) ergänzen.',
    aktiv: true,
  },
];

// --- Pflegeunternehmen (Partner) ---
export const PFLEGEUNTERNEHMEN: Pflegeunternehmen[] = [
  {
    id: 'pu-pflegeteam-berlin',
    standort_id: 'st-berlin',
    firmenname: 'Pflegeteam Berlin GmbH',
    rechtsform: 'gmbh',
    ik_nummer: '460123456',
    zulassung_72_sgb_xi: true,
    strasse: 'Kantstraße 12',
    plz: '10623',
    ort: 'Berlin',
    telefon: '030 98765432',
    email: 'kontakt@pflegeteam-berlin.de',
    website: 'https://pflegeteam-berlin.de',
    iban: 'DE00 1001 0010 0000 0000 01',
    status: 'partner',
    ansprechpartner: [
      {
        name: 'Sandra Koch',
        funktion: 'PDL',
        telefon: '030 98765433',
        email: 's.koch@pflegeteam-berlin.de',
        ist_hauptkontakt: true,
      },
    ],
    notiz: '',
    erstellt_am: '2026-01-15T09:00:00.000Z',
    geaendert_am: '2026-01-15T09:00:00.000Z',
  },
  {
    id: 'pu-sozialstation-mitte',
    standort_id: 'st-berlin',
    firmenname: 'Sozialstation Mitte e.V.',
    rechtsform: 'ev',
    ik_nummer: '460654321',
    zulassung_72_sgb_xi: true,
    strasse: 'Torstraße 100',
    plz: '10119',
    ort: 'Berlin',
    telefon: '030 66778899',
    email: 'info@sozialstation-mitte.de',
    website: 'https://sozialstation-mitte.de',
    iban: 'DE00 1001 0010 0000 0000 02',
    status: 'interessent',
    ansprechpartner: [
      {
        name: 'Anna Vogel',
        funktion: 'Geschäftsführung',
        telefon: '030 66778800',
        email: 'a.vogel@sozialstation-mitte.de',
        ist_hauptkontakt: true,
      },
    ],
    notiz: '',
    erstellt_am: '2026-02-01T09:00:00.000Z',
    geaendert_am: '2026-02-01T09:00:00.000Z',
  },
];

// --- Dienstleister (je Gewerk) ---
export const DIENSTLEISTER: Dienstleister[] = [
  { id: 'dl-sanitaer', name: 'Sanitär Schmidt GmbH', gewerk: 'sanitaer', ansprechpartner: 'M. Schmidt', telefon: '030 1110001', email: 'info@sanitaer-schmidt.de', strasse: 'Badstraße 5', plz: '13357', ort: 'Berlin', provision_prozent: 10, bewertung: 5, aktiv: true },
  { id: 'dl-fliesen', name: 'Fliesen Meister Berlin', gewerk: 'fliesen', ansprechpartner: 'K. Meister', telefon: '030 1110002', email: 'info@fliesen-meister.de', strasse: 'Kachelweg 8', plz: '10405', ort: 'Berlin', provision_prozent: 8, bewertung: 4, aktiv: true },
  { id: 'dl-trockenbau', name: 'Trockenbau Wand & Co.', gewerk: 'trockenbau', ansprechpartner: 'T. Wand', telefon: '030 1110003', email: 'info@trockenbau-wand.de', strasse: 'Plattenstraße 2', plz: '12043', ort: 'Berlin', provision_prozent: 10, aktiv: true },
  { id: 'dl-metallbau', name: 'Metallbau Stahl', gewerk: 'metallbau', ansprechpartner: 'S. Stahl', telefon: '030 1110004', email: 'info@metallbau-stahl.de', strasse: 'Eisenweg 14', plz: '13088', ort: 'Berlin', provision_prozent: 12, bewertung: 5, aktiv: true },
  { id: 'dl-schreiner', name: 'Schreinerei Holzmann', gewerk: 'schreiner', ansprechpartner: 'H. Holzmann', telefon: '030 1110005', email: 'info@schreinerei-holzmann.de', strasse: 'Holzallee 3', plz: '10247', ort: 'Berlin', provision_prozent: 10, aktiv: true },
  { id: 'dl-maurer', name: 'Bau & Putz Berlin', gewerk: 'maurer', ansprechpartner: 'B. Maurer', telefon: '030 1110006', email: 'info@bau-putz-berlin.de', strasse: 'Ziegelstraße 21', plz: '10117', ort: 'Berlin', provision_prozent: 12, aktiv: true },
  { id: 'dl-maler', name: 'Maler Farbenfroh', gewerk: 'maler', ansprechpartner: 'F. Farbe', telefon: '030 1110007', email: 'info@maler-farbenfroh.de', strasse: 'Pinselweg 9', plz: '10999', ort: 'Berlin', provision_prozent: 8, aktiv: true },
  { id: 'dl-grosshandel', name: 'Reha-Großhandel Nord', gewerk: 'grosshandel', ansprechpartner: 'R. Handel', telefon: '030 1110008', email: 'info@reha-grosshandel.de', strasse: 'Lagerstraße 50', plz: '13509', ort: 'Berlin', provision_prozent: 15, bewertung: 4, aktiv: true },
  { id: 'dl-elektro', name: 'Elektro Watt GmbH', gewerk: 'elektro', ansprechpartner: 'E. Watt', telefon: '030 1110009', email: 'info@elektro-watt.de', strasse: 'Stromstraße 7', plz: '10551', ort: 'Berlin', provision_prozent: 10, aktiv: true },
];

// --- Nachweistypen-Katalog ---
export const NACHWEIS_TYPEN: NachweisTyp[] = [
  { code: 'antrag_vor_beginn', bezeichnung: 'Antrag vor Maßnahmenbeginn', beschreibung: 'Antrag muss vor jedem Auftrags-/Umsetzungsdatum gestellt sein.', rechtsgrundlage_id: 'rg-40-4' },
  { code: 'begruendung', bezeichnung: 'Begründung mit Gesetzeskriterium', beschreibung: 'Bezug zu genau einem der drei §40-Kriterien.', rechtsgrundlage_id: 'rg-40-4' },
  { code: 'aerztliches_attest', bezeichnung: 'Ärztliches Attest', beschreibung: 'ICD-10-Diagnose + konkrete Funktionseinschränkung.' },
  { code: 'kostenvoranschlag', bezeichnung: 'Detaillierter Kostenvoranschlag', beschreibung: 'Positionsweise, nicht pauschal.' },
  { code: 'foto_ist_zustand', bezeichnung: 'Fotos Ist-Zustand', beschreibung: 'Dokumentation der Barriere vor Umbau.' },
  { code: 'einwilligung_dsgvo', bezeichnung: 'Einwilligung (DSGVO)', beschreibung: 'Datenschutzeinwilligung des Kunden.' },
  { code: 'abtretungserklaerung', bezeichnung: 'Abtretungserklärung §398 BGB', beschreibung: 'Für das 0-€-Modell (Direktabrechnung).', rechtsgrundlage_id: 'rg-398' },
  { code: 'vollmacht', bezeichnung: 'Vollmacht', beschreibung: 'Falls ein Angehöriger im Namen des Kunden handelt.' },
  { code: 'vermieterzustimmung', bezeichnung: 'Vermieterzustimmung', beschreibung: 'Bei Mietwohnungen für bauliche Eingriffe.' },
  { code: 'masskizze', bezeichnung: 'Maßskizze / Grundriss', beschreibung: 'Bei größeren baulichen Maßnahmen.' },
  { code: 'statiknachweis', bezeichnung: 'Statiknachweis', beschreibung: 'Bei Eingriff in tragende Wände.' },
];

// --- Pflichtnachweismatrix für §40 Abs.4 ---
function na(
  id: string,
  nachweis_code: NachweisAnforderung['nachweis_code'],
  pflicht: boolean,
  extra: Partial<NachweisAnforderung> = {},
): NachweisAnforderung {
  return { id, foerdertopf_id: 'ft-40-4', nachweis_code, pflicht, hinweis: '', ...extra };
}

export const NACHWEIS_ANFORDERUNGEN: NachweisAnforderung[] = [
  // Global (alle §40-Maßnahmen)
  na('na-1', 'antrag_vor_beginn', true),
  na('na-2', 'begruendung', true),
  na('na-3', 'aerztliches_attest', true),
  na('na-4', 'kostenvoranschlag', true),
  na('na-5', 'foto_ist_zustand', true),
  na('na-6', 'einwilligung_dsgvo', true),
  na('na-7', 'abtretungserklaerung', true, { hinweis: 'Pflicht für das 0-€-Modell.' }),
  // Bedingt
  na('na-8', 'vollmacht', false, { hinweis: 'Nur falls Angehöriger handelt.' }),
  na('na-9', 'vermieterzustimmung', true, { bedingung_wohnform: 'miete', hinweis: 'Nur bei Mietwohnung.' }),
  na('na-10', 'masskizze', true, { massnahme_kategorie: 'bad' }),
  na('na-11', 'masskizze', true, { massnahme_kategorie: 'rampe' }),
  na('na-12', 'statiknachweis', true, { massnahme_kategorie: 'tueren', hinweis: 'Bei tragender Wand.' }),
  na('na-13', 'masskizze', true, { massnahme_kategorie: 'treppen_lift' }),
];

// --- Fristenregeln ---
export const FRIST_REGELN: FristRegel[] = [
  {
    id: 'fr-40-4',
    foerdertopf_id: 'ft-40-4',
    entscheidungsfrist_tage: 21,
    frist_mit_md_tage: 35,
    genehmigungsfiktion: true,
    widerspruch_frist_tage: 30,
    umsetzung_frist_tage: 180,
    rechtsgrundlage_id: 'rg-frist',
  },
];

// --- Widerspruchsgründe ---
export const WIDERSPRUCHSGRUENDE: Widerspruchsgrund[] = [
  { id: 'wg-funktionsbezug', code: 'WG-FUNKT', bezeichnung: 'Pflegerelevanz dargelegt', argumentation: 'Konkreter Bezug zu einem der drei §40-Kriterien mit Diagnose und Funktionseinschränkung nachweisen.', rechtsgrundlage_id: 'rg-40-4' },
  { id: 'wg-attest', code: 'WG-ATTEST', bezeichnung: 'Fachärztliches Attest nachgereicht', argumentation: 'Neues, detailliertes fachärztliches Attest mit ICD-10 und Funktionsbefund.' },
  { id: 'wg-wirtschaftlichkeit', code: 'WG-WIRT', bezeichnung: 'Wirtschaftlichkeit', argumentation: 'Vergleich: ambulanter Umbau deutlich günstiger als (drohende) stationäre Unterbringung.' },
  { id: 'wg-bsg', code: 'WG-BSG', bezeichnung: 'BSG-Rechtsprechung', argumentation: 'Verweis auf einschlägige BSG-Urteile zur Förderfähigkeit fest eingebauter Maßnahmen.', rechtsgrundlage_id: 'rg-bsg-4-16' },
  { id: 'wg-fiktion', code: 'WG-FIKTION', bezeichnung: 'Genehmigungsfiktion', argumentation: 'Entscheidungsfrist überschritten — Leistung gilt als genehmigt.', rechtsgrundlage_id: 'rg-frist' },
];

// --- Ablehnungsgründe (typisch §40) inkl. empfohlener Widerspruchsstrategie ---
export const ABLEHNUNGSGRUENDE: Ablehnungsgrund[] = [
  { id: 'ag-erforderlichkeit', code: 'AG-ERF', bezeichnung: 'Maßnahme nicht erforderlich', beschreibung: 'Kasse sieht zumutbare Alternative oder keine Erforderlichkeit.', haeufigkeit: 'haeufig', empfohlene_reaktion: 'Funktionseinschränkung und Sturzrisiko konkret belegen; Attest verstärken.', widerspruchsgrund_ids: ['wg-funktionsbezug', 'wg-attest'] },
  { id: 'ag-pflegebezug', code: 'AG-PFLEGE', bezeichnung: 'Fehlender Pflegebezug', beschreibung: 'Maßnahme wird nicht als pflegeerleichternd anerkannt.', haeufigkeit: 'gelegentlich', empfohlene_reaktion: 'Bezug zur häuslichen Pflege explizit nach §40 Abs.4 darstellen.', widerspruchsgrund_ids: ['wg-funktionsbezug'] },
  { id: 'ag-wirtschaftlichkeit', code: 'AG-WIRT', bezeichnung: 'Unwirtschaftlich / überteuert', beschreibung: 'Kostenvoranschlag als zu hoch bewertet.', haeufigkeit: 'gelegentlich', empfohlene_reaktion: 'Marktüblichkeit belegen; Wirtschaftlichkeit ggü. stationärer Alternative aufzeigen.', widerspruchsgrund_ids: ['wg-wirtschaftlichkeit'] },
  { id: 'ag-unterlagen', code: 'AG-UNTERL', bezeichnung: 'Unvollständige Unterlagen', beschreibung: 'Attest/Kostenvoranschlag/Fotos fehlen oder unzureichend.', haeufigkeit: 'haeufig', empfohlene_reaktion: 'Fehlende Pflichtnachweise vollständig nachreichen (Vollständigkeitsprüfung).', widerspruchsgrund_ids: ['wg-attest'] },
  { id: 'ag-beginn', code: 'AG-BEGINN', bezeichnung: 'Vor Antragstellung begonnen', beschreibung: 'Maßnahme wurde vor der Antragstellung begonnen.', haeufigkeit: 'selten', empfohlene_reaktion: 'Vermeidbar: harte Vorab-Prüfung „Antrag vor Beginn". Kein erfolgversprechender Widerspruch.', widerspruchsgrund_ids: [] },
  { id: 'ag-zustaendigkeit', code: 'AG-GKV', bezeichnung: 'Zuständigkeit GKV (§33 SGB V)', beschreibung: 'Kasse stuft als Hilfsmittel der Krankenversicherung ein.', haeufigkeit: 'selten', empfohlene_reaktion: 'Feste Einbindung in die Bausubstanz betonen (BSG-Rechtsprechung).', widerspruchsgrund_ids: ['wg-bsg'] },
];

// --- Dokumentenbibliothek (Vorlagen) ---
const STD_PLATZHALTER = [
  '{{kunde.vorname}}',
  '{{kunde.nachname}}',
  '{{kunde.strasse}}',
  '{{kunde.plz}}',
  '{{kunde.ort}}',
  '{{kunde.versichertennummer}}',
  '{{kunde.pflegegrad}}',
  '{{kasse.name}}',
  '{{datum}}',
];

export const DOKUMENT_VORLAGEN: DokumentVorlage[] = [
  {
    id: 'dv-anschreiben',
    code: 'DV-ANSCHREIBEN',
    bezeichnung: 'Anschreiben an die Pflegekasse',
    kategorie: 'anschreiben',
    beschreibung: 'Begleitschreiben zum §40-Antrag.',
    foerdertopf_id: 'ft-40-4',
    format: 'pdf',
    platzhalter: STD_PLATZHALTER,
    pflicht: true,
    version: 1,
    aktiv: true,
  },
  {
    id: 'dv-antrag-40-4',
    code: 'DV-ANTRAG-40-4',
    bezeichnung: 'Antrag § 40 Abs. 4 SGB XI',
    kategorie: 'antrag',
    beschreibung: 'Hauptantrag auf wohnumfeldverbessernde Maßnahmen.',
    foerdertopf_id: 'ft-40-4',
    rechtsgrundlage_id: 'rg-40-4',
    format: 'pdf',
    platzhalter: [...STD_PLATZHALTER, '{{massnahme.bezeichnung}}', '{{foerderbetrag}}', '{{begruendung}}'],
    pflicht: true,
    version: 1,
    aktiv: true,
  },
  {
    id: 'dv-vollmacht',
    code: 'DV-VOLLMACHT',
    bezeichnung: 'Vollmacht (Angehörige)',
    kategorie: 'vollmacht',
    beschreibung: 'Vollmacht zur Vertretung gegenüber der Pflegekasse.',
    format: 'pdf',
    platzhalter: [...STD_PLATZHALTER, '{{angehoeriger.name}}'],
    pflicht: false,
    version: 1,
    aktiv: true,
  },
  {
    id: 'dv-dsgvo',
    code: 'DV-DSGVO',
    bezeichnung: 'DSGVO-Einwilligung',
    kategorie: 'einwilligung',
    beschreibung: 'Datenschutzrechtliche Einwilligung des Kunden.',
    format: 'pdf',
    platzhalter: STD_PLATZHALTER,
    pflicht: true,
    version: 1,
    aktiv: true,
  },
  {
    id: 'dv-abtretung',
    code: 'DV-ABTRETUNG',
    bezeichnung: 'Abtretungserklärung § 398 BGB',
    kategorie: 'abtretungserklaerung',
    beschreibung: 'Abtretung an CareCoach Pro für die Direktabrechnung (0-€-Modell).',
    rechtsgrundlage_id: 'rg-398',
    format: 'pdf',
    platzhalter: [...STD_PLATZHALTER, '{{foerderbetrag}}'],
    pflicht: true,
    version: 1,
    aktiv: true,
  },
  {
    id: 'dv-einwilligung-massnahme',
    code: 'DV-EINWILLIGUNG',
    bezeichnung: 'Einwilligung Maßnahme & Fotodokumentation',
    kategorie: 'einwilligung',
    beschreibung: 'Zustimmung zur Maßnahme und zur Fotodokumentation des Ist-Zustands.',
    format: 'pdf',
    platzhalter: STD_PLATZHALTER,
    pflicht: false,
    version: 1,
    aktiv: true,
  },
  {
    id: 'dv-kostenvoranschlag',
    code: 'DV-KOSTENVORANSCHLAG',
    bezeichnung: 'Kostenvoranschlag (detailliert)',
    kategorie: 'kostenvoranschlag',
    beschreibung: 'Positionsweiser Kostenvoranschlag aus der Materialliste.',
    foerdertopf_id: 'ft-40-4',
    format: 'pdf',
    platzhalter: [...STD_PLATZHALTER, '{{massnahme.bezeichnung}}', '{{positionen}}', '{{summe_brutto}}'],
    pflicht: true,
    version: 1,
    aktiv: true,
  },
  {
    id: 'dv-attest-anforderung',
    code: 'DV-ATTEST',
    bezeichnung: 'Attest-Anforderung an den Arzt',
    kategorie: 'attest',
    beschreibung: 'Vorlage zur Anforderung des ärztlichen Attests (ICD-10 + Funktionsbefund).',
    format: 'pdf',
    platzhalter: [...STD_PLATZHALTER, '{{diagnose}}', '{{icd10}}'],
    pflicht: true,
    version: 1,
    aktiv: true,
  },
  {
    id: 'dv-widerspruch',
    code: 'DV-WIDERSPRUCH',
    bezeichnung: 'Widerspruch gegen Ablehnung',
    kategorie: 'widerspruch',
    beschreibung: 'Widerspruchsschreiben mit Begründungsbausteinen.',
    rechtsgrundlage_id: 'rg-widerspruch',
    format: 'pdf',
    platzhalter: [...STD_PLATZHALTER, '{{ablehnungsgrund}}', '{{widerspruchsbegruendung}}'],
    pflicht: false,
    version: 1,
    aktiv: true,
  },
  {
    id: 'dv-nachweis-checkliste',
    code: 'DV-CHECKLISTE',
    bezeichnung: 'Nachweis-Checkliste (Antragspaket)',
    kategorie: 'antrag',
    beschreibung: 'Übersicht aller Pflichtnachweise mit Status (Vollständigkeitsprüfung).',
    foerdertopf_id: 'ft-40-4',
    format: 'pdf',
    platzhalter: [...STD_PLATZHALTER, '{{nachweise}}'],
    pflicht: false,
    version: 1,
    aktiv: true,
  },
];
